<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\**" />
    <EmbeddedResource Remove="Assets\**" />
    <None Remove="Assets\**" />
    <Page Remove="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Emoji.Wpf" Version="0.3.4" />
    <PackageReference Include="LibVLCSharp" Version="3.10.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23.1" />
  </ItemGroup>

</Project>
